# Certificate Issues using Let's Encrypt's Staging servers

apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  # The name of this Certificate Issuer in the cluster
  name: letsencrypt-staging
  # Put it in the same namespace as Cert Manager
  namespace: cert-manager
spec:
  acme:
    # The staging servers for Let's Encrypt
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: <YOUR E-MAIL>
    privateKeySecretRef:
      name: letsencrypt-staging
    solvers:
    - selector: {}
      http01:
        ingress:
          # For use with the Traefik Ingress Controller
          class: traefik